name: '#{Carlos_Espejo}'
timezone: America/New_York
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate
  - jemoji
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  
