title: '#{Carlos_Espejo}'
description: Rubyist
theme: jekyll-theme-slate
timezone: America/New_York
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jemoji
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
