title: '#{Carlos_Espejo}'
description: Building at the intersection of AI agents and DevOps
url: https://carlosespejo.com
github_username: CarlosEspejo
timezone: America/New_York
sass:
  quiet_deps: true
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jemoji
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
